# Generated by Django 5.0.2 on 2024-02-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_booking_returning_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturningBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returning_date_time', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.booking')),
            ],
        ),
    ]
