# Generated by Django 5.0.2 on 2024-02-20 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_resettoken_expires_at_alter_resettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 13, 27, 7, 15361, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resettoken',
            name='token',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
