# Generated by Django 5.0.2 on 2024-02-21 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_resettoken_expires_at_alter_resettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 4, 52, 42, 785349, tzinfo=datetime.timezone.utc)),
        ),
    ]
