# Generated by Django 5.0.2 on 2024-02-21 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_resettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 5, 6, 56, 665344, tzinfo=datetime.timezone.utc)),
        ),
    ]
